apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: worker
        image: firemanxbr/veriff:0.1.13
        command: ["celery"]
        args: ["-A", "task", "worker", "--loglevel=info"]
        volumeMounts:
          - mountPath: "/svc/images/"
            name: task-pv-storage
